algoritmo "Creuza"
// Função : Curar o alzheimer de Creuza
// Autor :  Deve ser Leonardo Zanotti
// Data : 09-Feb-18
// Seção de Declarações 
var
   idade, ano_atual, ano_nasc: inteiro
inicio
      escreval("Em que ano nós estamos?")
      leia(ano_atual)
      escreval("Em que ano eu nasci?")
      leia(ano_nasc)
      idade <- ano_atual - ano_nasc
      escreva("Minha idade é",idade," anos")
fimalgoritmo
